# Generated by Django 5.1.2 on 2024-12-19 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_basic_infos_app', '0005_alter_rating_business_user_alter_rating_reviewer'),
        ('coderr_user_profile_app', '0003_delete_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='business_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_ratings', to='coderr_user_profile_app.profile'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_ratings', to='coderr_user_profile_app.profile'),
        ),
    ]
