# Generated by Django 5.1.2 on 2024-12-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_basic_infos_app', '0006_alter_rating_business_user_alter_rating_reviewer'),
        ('coderr_user_profile_app', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('reviewer', 'business_user')},
        ),
    ]
