# Generated by Django 5.1.2 on 2024-12-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_user_profile_app', '0002_remove_profile_file_remove_profile_uploaded_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
