# Generated by Django 5.1.2 on 2024-12-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_order_offer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
