# Generated by Django 5.1.2 on 2024-12-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_order_offer_app', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='min_delivery_time',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
