# Generated by Django 5.1.2 on 2024-12-19 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_order_offer_app', '0004_offer_min_delivery_time'),
        ('coderr_user_profile_app', '0003_delete_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='coderr_user_profile_app.profile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='coderr_user_profile_app.profile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='coderr_order_offer_app.offerdetail'),
        ),
    ]
